/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intreprisemanagementsystem;

import static intreprisemanagementsystem.ohada_log2.bus;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DOSHE
 */
public class bayeur_ohada extends javax.swing.JPanel {

 Connection con=null;
PreparedStatement pst=null;
ResultSet rs= null;
String etrolls;
    public bayeur_ohada() {
        initComponents();
          con=JavaDbConnect.dbConnect();
          attLIST_from_EMPLOYEView_used();
    }
 public void save(){
    
     try{
     String sql="INSERT INTO `ohada`(`NAME`, `CODE`, `COMPTEMERE`, `CODEMERE`, `CLASS`,SUBSTR)"+"VALUE(?,?,?,?,?,?)";
     pst=con.prepareStatement(sql);
     
     pst.setString(1,bus.getText());
     pst.setString(2,code.getText()); 
     pst.setString(3,compte.getText()); 
     pst.setString(4,codem.getText());
     pst.setString(5,classe.getText());
     pst.setString(6,"41");
      pst.executeUpdate();
      JOptionPane.showMessageDialog(null,"Saved"); 
     }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
     
    }
 public void attLIST_from_EMPLOYEView_used()
    {
        try{
       
      
     
       String sql="SELECT  CODE AS 'ACCOUNT',`NAME` AS 'ACCOUNT DESCRIPTION', `CLASS` FROM `ohada` WHERE COMPTEMERE='"+compte.getText()+"'";
       pst = con.prepareStatement(sql);
      rs= pst.executeQuery();
     
       jTable2.setModel(DbUtils.resultSetToTableModel(rs));
       DefaultTableCellRenderer centre =new DefaultTableCellRenderer();
       TableColumn col0=jTable2.getColumnModel().getColumn(0);
       
        TableColumn col1=jTable2.getColumnModel().getColumn(1);
        TableColumn col2=jTable2.getColumnModel().getColumn(2);
        
       
       
      
       col0.setPreferredWidth(50);
       col1.setPreferredWidth(200);
       col2.setPreferredWidth(50);
       
        centre.setHorizontalAlignment(JLabel.CENTER);
        jTable2.getColumnModel().getColumn(0).setCellRenderer(centre);
         centre.setHorizontalAlignment(JLabel.CENTER);
        jTable2.getColumnModel().getColumn(2).setCellRenderer(centre);
       
      
        
    }catch(SQLException ex ){
     JOptionPane.showMessageDialog(null, ex);
}
}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buss = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        compte = new javax.swing.JTextField();
        codem = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        classe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Business Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 10));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 650, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Denamination:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Code:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 80, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Code");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Code");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 60, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 140, 30));

        buss.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One Business" }));
        buss.setBorder(null);
        buss.setEnabled(false);
        buss.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                bussPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel3.add(buss, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 271, 270, 30));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 650, 140));

        bus.setEditable(false);
        bus.setBackground(new java.awt.Color(240, 240, 241));
        bus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 650, -1));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 160));

        compte.setEditable(false);
        compte.setBackground(new java.awt.Color(240, 240, 241));
        compte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compte.setText("Clients, organismes internationaux");
        jPanel3.add(compte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, -1));

        codem.setEditable(false);
        codem.setBackground(new java.awt.Color(240, 240, 241));
        codem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codem.setText("41");
        jPanel3.add(codem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 100, -1));

        code.setEditable(false);
        code.setBackground(new java.awt.Color(240, 240, 241));
        code.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 100, -1));

        classe.setEditable(false);
        classe.setBackground(new java.awt.Color(240, 240, 241));
        classe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classe.setText("4");
        jPanel3.add(classe, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Class");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
save();
        attLIST_from_EMPLOYEView_used();      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bussPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_bussPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_bussPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTextField bus = new javax.swing.JTextField();
    private javax.swing.JComboBox<String> buss;
    private javax.swing.JTextField classe;
    private javax.swing.JTextField code;
    private javax.swing.JTextField codem;
    private javax.swing.JTextField compte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
