/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intreprisemanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dosh
 */
public class NewJInternalFrameMateriaux_Recycle_bin extends javax.swing.JInternalFrame {
 Connection con=null;
PreparedStatement pst=null;
ResultSet rs= null;
 DefaultTableModel mode;
 String rolls;
    public NewJInternalFrameMateriaux_Recycle_bin() {
        initComponents();
              con=JavaDbConnect.dbConnect();
        calltable();
    }
    
    public void calltable(){
     try{
       
      
       String sql="SELECT  `MATR_ID`, `MATR_NAME`, `MATR_DESCR`, `MATR_QTY`, `UNITY`, `MATR_QTY_IN`, `MATR_QTY_OUT`, `MATR_DATE`, `DEL_DATES` FROM `backupmateriaux` ";
       //String sql="SELECT SUM(`CREDIT_PT`) from `facture_fournisseur` WHERE `COMPTE`='LEVI LIKOYO'";
       pst = con.prepareStatement(sql);
      rs= pst.executeQuery();
    //  if(rs.next()){
       jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       
       TableColumn col0=jTable1.getColumnModel().getColumn(0);
       TableColumn col1=jTable1.getColumnModel().getColumn(1);
       TableColumn col2=jTable1.getColumnModel().getColumn(2);
       TableColumn col3=jTable1.getColumnModel().getColumn(3);
       TableColumn col4=jTable1.getColumnModel().getColumn(4);
       TableColumn col5=jTable1.getColumnModel().getColumn(5);
       TableColumn col6=jTable1.getColumnModel().getColumn(6);
       TableColumn col7=jTable1.getColumnModel().getColumn(7);
       TableColumn col8=jTable1.getColumnModel().getColumn(8);
      
      
      // // `LIBELLE`, `ENTRE`, `SORTIE`, `USD`, `FC`, `SH`, `USED`, `DATES`, `PROJET`, `PROJECT_ID`, `USD1`, `NUM` FROM 
       col0.setPreferredWidth(50);
       col1.setPreferredWidth(70);
       col2.setPreferredWidth(100);
       col3.setPreferredWidth(30);
       col4.setPreferredWidth(30);
       col5.setPreferredWidth(30);
       col6.setPreferredWidth(30);
       col7.setPreferredWidth(50);
       col8.setPreferredWidth(50);
      
       
     // }
    }catch(SQLException ex ){
     JOptionPane.showMessageDialog(null, ex);
}
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MATERIALS_RECYCLE_BIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(504, 504, 504)
                .addComponent(jLabel1)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
