/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canalplus.cell;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Doshe PC
 */
public class panelAction extends javax.swing.JPanel {

    /**
     * Creates new form panelAction
     */
    public panelAction() {
        initComponents();
    }
public void initEvent(TableActionEvent event, int row){
cmdnew.addActionListener(new ActionListener(){

@Override
public void actionPerformed(ActionEvent ae){
event.onnew(row);

}
});



cmddelet.addActionListener(new ActionListener(){

@Override
public void actionPerformed(ActionEvent ae){
event.ondelete(row);

}
});


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmddelet = new canalplus.cell.ActionButton();
        cmdnew = new canalplus.cell.ActionButton();

        cmddelet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canalplus/cell/icons8-clear-symbol-16.png"))); // NOI18N

        cmdnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canalplus/cell/icons8-edit-16.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdnew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmddelet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmddelet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(cmdnew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private canalplus.cell.ActionButton cmddelet;
    private canalplus.cell.ActionButton cmdnew;
    // End of variables declaration//GEN-END:variables
}
