package sample.notification;


import intreprisemanagementsystem.JavaDbConnect;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import journals.store_setting;
import net.proteanit.sql.DbUtils;
import raven.glasspanepopup.GlassPanePopup;
import sample.message.Message;

/**
 *
 * @author RAVEN
 */
public class num_entre_stock extends javax.swing.JPanel {
  private Connection con;
private Statement st;
PreparedStatement pst=null;
ResultSet rs= null;
DefaultTableModel mode;
    public num_entre_stock(Icon icon,String num_fiche, String fournisseur, String montant, String dates) {
        initComponents();
          con=JavaDbConnect.dbConnect();
           
        pic.setIcon(icon);
        lbnum_fiche.setText(num_fiche);
        lbfournisseur.setText(fournisseur);
        lbmontant.setText(montant);
        lbdate.setText(dates);
        
    }

    public void select(){
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic = new sample.swing.ImageAvatar();
        lbfournisseur = new javax.swing.JLabel();
        lbmontant = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        lbnum_fiche = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample/notification/download (1).png"))); // NOI18N
        pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picMouseClicked(evt);
            }
        });

        lbfournisseur.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        lbfournisseur.setForeground(new java.awt.Color(106, 106, 106));
        lbfournisseur.setText("Num fiche");
        lbfournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbfournisseurMouseClicked(evt);
            }
        });

        lbmontant.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        lbmontant.setForeground(new java.awt.Color(134, 134, 134));
        lbmontant.setText("Description");
        lbmontant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbmontantMouseClicked(evt);
            }
        });

        lbdate.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        lbdate.setForeground(new java.awt.Color(134, 134, 134));
        lbdate.setText("a day ago");
        lbdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdateMouseClicked(evt);
            }
        });

        lbnum_fiche.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbnum_fiche.setForeground(new java.awt.Color(106, 106, 106));
        lbnum_fiche.setText("Num fiche");
        lbnum_fiche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnum_ficheMouseClicked(evt);
            }
        });

        jLabel1.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intreprisemanagementsystem/icons8-eye-20.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbfournisseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbnum_fiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbmontant, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lbdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbnum_fiche)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbfournisseur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbmontant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbdate))
                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbfournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbfournisseurMouseClicked
select();  //JOptionPane.showMessageDialog(null,lbName.getText());       // TODO add your handling code here:
    }//GEN-LAST:event_lbfournisseurMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
select();         // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void lbmontantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbmontantMouseClicked
select();          // TODO add your handling code here:
    }//GEN-LAST:event_lbmontantMouseClicked

    private void lbdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdateMouseClicked
select();          // TODO add your handling code here:
    }//GEN-LAST:event_lbdateMouseClicked

    private void lbnum_ficheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnum_ficheMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbnum_ficheMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
  store_setting.jLabel44.setText(lbnum_fiche.getText());
  store_setting.item_id2.setText(lbnum_fiche.getText());
        try{
        PreparedStatement ps = con.prepareStatement("Select * from stock_mvm where NUM='"+lbnum_fiche.getText()+"'");  
        ResultSet rs=ps.executeQuery();
        DefaultTableModel tm = (DefaultTableModel)store_setting.jTable6.getModel();
        tm.setRowCount(0);

      while(rs.next()){//  `BIN`, `REF`, `NOM`
            Object o[] = {rs.getString("REF"),rs.getString("NOM"),"EA",rs.getString("QTY_R"),rs.getDouble("QTY_D"),rs.getString("DEPOT")};
            tm.addRow(o);
 }
      mode=new DefaultTableModel();

            TableColumn col0 = store_setting.jTable6.getColumnModel().getColumn(0);
            TableColumn col1 = store_setting.jTable6.getColumnModel().getColumn(1);
            TableColumn col2 = store_setting.jTable6.getColumnModel().getColumn(2);
            TableColumn col3 = store_setting.jTable6.getColumnModel().getColumn(3);
            TableColumn col4=  store_setting.jTable6.getColumnModel().getColumn(4);
             TableColumn col5=  store_setting.jTable6.getColumnModel().getColumn(4);

            col0.setPreferredWidth(100);
            col1.setPreferredWidth(150);
            col2.setPreferredWidth(50);
            col3.setPreferredWidth(50);
            col4.setPreferredWidth(50);
            col5.setPreferredWidth(100);
     
    }catch(SQLException ex ){JOptionPane.showMessageDialog(null, ex);} 
        
     /*   
        try{
       String sql="SELECT NUM as 'Bin loc',NAME_TO as 'Ref. Numbers',DESCR as 'Descption',Qty,Qty_c as 'Qty received',Store FROM  recu where NUM_FICHE='"+lbnum_fiche.getText()+"'";  
            pst = con.prepareStatement(sql);
            rs= pst.executeQuery();

            store_setting.jTable6.setModel(DbUtils.resultSetToTableModel(rs));
            mode=new DefaultTableModel();

            TableColumn col0 = store_setting.jTable6.getColumnModel().getColumn(0);
            TableColumn col1 = store_setting.jTable6.getColumnModel().getColumn(1);
            TableColumn col2 = store_setting.jTable6.getColumnModel().getColumn(2);
            TableColumn col3 = store_setting.jTable6.getColumnModel().getColumn(3);
            TableColumn col4=  store_setting.jTable6.getColumnModel().getColumn(4);
             TableColumn col5=  store_setting.jTable6.getColumnModel().getColumn(4);

            col0.setPreferredWidth(50);
            col1.setPreferredWidth(100);
            col2.setPreferredWidth(200);
            col3.setPreferredWidth(50);
            col4.setPreferredWidth(50);
            col5.setPreferredWidth(100);
             

        }catch(SQLException ex ){JOptionPane.showMessageDialog(null, ex);} 
*/// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picMouseClicked
        select();
        // TODO add your handling code here:
    }//GEN-LAST:event_picMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbfournisseur;
    private javax.swing.JLabel lbmontant;
    private javax.swing.JLabel lbnum_fiche;
    private sample.swing.ImageAvatar pic;
    // End of variables declaration//GEN-END:variables
}
